version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - node/install
      - node/install-packages
      - run:
          name: Run build
          command: npm run build
